# This project is proprietary software (All Rights Reserved).
# We do not accept community funding or sponsorships.
# For commercial licensing inquiries, see LICENSE or contact the maintainer.
custom: ['https://github.com/Liuyifeidashuaibi/FnixAgent/blob/main/LICENSE']
