"""OfficeAgent 可观测性模块 — Phase 2.10。"""
from officeagent.core.observability.metrics import (
    setup_metrics,
    is_enabled,
    record_login,
    record_user_active,
    record_user_registration,
    record_chat_message,
    record_document_operation,
    record_task_created,
    record_langgraph_node,
    record_flywheel_trigger,
    update_topology_stats,
    record_tool_execution,
    record_tool_error,
    record_permission_denied,
    record_rate_limit_triggered,
    record_injection_blocked,
    record_sensitive_hit,
    record_mfa_challenge,
    record_audit_log,
    record_llm_call,
    record_llm_tokens,
    record_llm_error,
)
from officeagent.core.observability.stats import (
    StatsAggregator,
    StatsProvider,
    get_stats_aggregator,
    register_default_providers,
    reset_stats_aggregator,
)

__all__ = [
    "setup_metrics",
    "is_enabled",
    "record_login",
    "record_user_active",
    "record_user_registration",
    "record_chat_message",
    "record_document_operation",
    "record_task_created",
    "record_langgraph_node",
    "record_flywheel_trigger",
    "update_topology_stats",
    "record_tool_execution",
    "record_tool_error",
    "record_permission_denied",
    "record_rate_limit_triggered",
    "record_injection_blocked",
    "record_sensitive_hit",
    "record_mfa_challenge",
    "record_audit_log",
    "record_llm_call",
    "record_llm_tokens",
    "record_llm_error",
    # P2-02: 统一指标聚合
    "StatsAggregator",
    "StatsProvider",
    "get_stats_aggregator",
    "register_default_providers",
    "reset_stats_aggregator",
]
