"""
审计日志核心模块(Phase 2.5)。

导出:
    - AuditLogger: 审计日志写入器(支持哈希链防篡改)
    - 审计动作常量(AUDIT_*)
    - verify_hash_chain: 哈希链完整性校验
"""
from officeagent.core.audit.logger import (
    AuditLogger,
    AuditLogDTO,
    verify_hash_chain,
    # 审计动作常量
    AUDIT_LOGIN_SUCCESS,
    AUDIT_LOGIN_FAILED,
    AUDIT_LOGOUT,
    AUDIT_MFA_ENABLE,
    AUDIT_MFA_DISABLE,
    AUDIT_MFA_CHALLENGE,
    AUDIT_MFA_VERIFY_FAILED,
    AUDIT_PERMISSION_DENIED,
    AUDIT_USER_DISABLE,
    AUDIT_USER_ENABLE,
    AUDIT_USER_ROLE_CHANGE,
    AUDIT_PASSWORD_RESET,
    AUDIT_CONFIG_UPDATE,
    AUDIT_SENSITIVE_HIT,
    AUDIT_INJECTION_BLOCKED,
    AUDIT_DATA_EXPORT,
    AUDIT_DATA_DELETE,
    AUDIT_SSO_LOGIN,
    AUDIT_LDAP_LOGIN,
    AUDIT_FACTOR_FORCE_DISABLED,
    AUDIT_PRIVACY_EXPORT,
    AUDIT_ACCOUNT_DELETE_REQUEST,
    AUDIT_ACCOUNT_DELETE_CANCEL,
    AUDIT_ACCOUNT_HARD_DELETED,
    AUDIT_MODERATION_INPUT_BLOCKED,
    AUDIT_MODERATION_OUTPUT_BLOCKED,
    ALL_AUDIT_ACTIONS,
)

__all__ = [
    "AuditLogger",
    "AuditLogDTO",
    "verify_hash_chain",
    "AUDIT_LOGIN_SUCCESS",
    "AUDIT_LOGIN_FAILED",
    "AUDIT_LOGOUT",
    "AUDIT_MFA_ENABLE",
    "AUDIT_MFA_DISABLE",
    "AUDIT_MFA_CHALLENGE",
    "AUDIT_MFA_VERIFY_FAILED",
    "AUDIT_PERMISSION_DENIED",
    "AUDIT_USER_DISABLE",
    "AUDIT_USER_ENABLE",
    "AUDIT_USER_ROLE_CHANGE",
    "AUDIT_PASSWORD_RESET",
    "AUDIT_CONFIG_UPDATE",
    "AUDIT_SENSITIVE_HIT",
    "AUDIT_INJECTION_BLOCKED",
    "AUDIT_DATA_EXPORT",
    "AUDIT_DATA_DELETE",
    "AUDIT_SSO_LOGIN",
    "AUDIT_LDAP_LOGIN",
    "AUDIT_FACTOR_FORCE_DISABLED",
    "AUDIT_PRIVACY_EXPORT",
    "AUDIT_ACCOUNT_DELETE_REQUEST",
    "AUDIT_ACCOUNT_DELETE_CANCEL",
    "AUDIT_ACCOUNT_HARD_DELETED",
    "AUDIT_MODERATION_INPUT_BLOCKED",
    "AUDIT_MODERATION_OUTPUT_BLOCKED",
    "ALL_AUDIT_ACTIONS",
]
