apiVersion: v1
kind: Service
metadata:
  name: {{ include "officeagent.fullname" . }}
  labels:
    {{- include "officeagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.officeagent.service.type }}
  ports:
    - port: {{ .Values.officeagent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "officeagent.selectorLabels" . | nindent 4 }}
